package com.agentdeck.app.domain.chat

import androidx.compose.runtime.Immutable
import com.agentdeck.app.data.chat.RpcRequestId
import com.agentdeck.app.domain.model.AgentCard
import com.agentdeck.app.domain.model.CodexPermissionLevel

enum class ChatItemKind {
    USER,
    ASSISTANT,
    REASONING,
    COMMAND,
    FILE_CHANGE,
    TOOL,
    ERROR,
}

@Immutable
data class FilePatch(
    val path: String,
    /** Patch change kind from the protocol: add / delete / update. */
    val kind: String,
    val diff: String,
)

@Immutable
data class ChatItem(
    val id: String,
    val kind: ChatItemKind,
    val text: String,
    val detail: String? = null,
    val status: String? = null,
    val patches: List<FilePatch> = emptyList(),
    val turnId: String? = null,
)

enum class ChatAttachmentKind {
    IMAGE,
    FILE,
}

enum class ChatAttachmentFormat(val adapterId: String?) {
    IMAGE(null),
    TEXT("text"),
    PDF("pdf"),
    DOCX("docx"),
    XLSX("xlsx"),
}

@Immutable
data class ChatAttachment(
    val id: String,
    val name: String,
    val mimeType: String,
    val sizeBytes: Long,
    /** Absolute path visible inside the embedded Ubuntu runtime. */
    val guestPath: String,
    val kind: ChatAttachmentKind,
    val format: ChatAttachmentFormat,
    /** Normalized text generated by the private file adapter for non-image files. */
    val preparedGuestPath: String? = null,
    val wasTruncated: Boolean = false,
)

@Immutable
data class CodexRuntime(
    val model: String,
    val provider: String,
)

@Immutable
data class CodexModelOption(
    val id: String,
    val displayName: String = id,
    val isDefault: Boolean = false,
    /** Null means a managed/third-party catalog did not publish capability metadata. */
    val inputModalities: Set<String>? = null,
)

@Immutable
data class CodexModelPage(
    val models: List<CodexModelOption>,
    val nextCursor: String?,
)

@Immutable
data class CodexHistoryPage(
    /** Items are always normalized to oldest-first display order. */
    val items: List<ChatItem>,
    val nextCursor: String?,
)

enum class ApprovalKind {
    COMMAND,
    FILE_CHANGE,
    PERMISSIONS,
    MCP_TOOL,
}

@Immutable
data class ChatApproval(
    val requestId: RpcRequestId,
    val kind: ApprovalKind,
    val title: String,
    val detail: String,
    val requestedPermissions: String? = null,
    /** Whether Codex advertised a session-scoped approval choice for this request. */
    val supportsSessionApproval: Boolean = true,
    /** Item that triggered the approval; used to attach live patch data for previews. */
    val itemId: String? = null,
)

@Immutable
data class ToolUserInputOption(
    val label: String,
    val description: String,
)

@Immutable
data class ToolUserInputQuestion(
    val id: String,
    val header: String,
    val question: String,
    val options: List<ToolUserInputOption> = emptyList(),
    /** When true the user may answer with free text instead of a listed option. */
    val isOther: Boolean = false,
    /** When true the answer is sensitive and must be masked in the UI. */
    val isSecret: Boolean = false,
)

/**
 * A pending `item/tool/requestUserInput` server request. Mirrors the approval
 * slot semantics: one is shown at a time while additional requests wait in a
 * bounded FIFO, and every slot clears on disconnect.
 */
@Immutable
data class ChatUserInputRequest(
    val requestId: RpcRequestId,
    val itemId: String,
    val questions: List<ToolUserInputQuestion>,
)

/** A message composed while a turn/approval was in flight, to be sent as a new turn. */
@Immutable
data class QueuedChatMessage(
    val id: String,
    val text: String,
    val attachments: List<ChatAttachment> = emptyList(),
)

/**
 * Errors surfaced by the chat pipeline, classified in the ViewModel layer so the
 * UI only renders them. [raw] keeps the original message for technical detail mode.
 */
@Immutable
sealed interface ChatError {
    val raw: String

    @Immutable
    data class Auth(override val raw: String) : ChatError

    @Immutable
    data class Network(override val raw: String) : ChatError

    @Immutable
    data class Model(override val raw: String) : ChatError

    @Immutable
    data class Attachment(override val raw: String) : ChatError

    @Immutable
    data class Unknown(override val raw: String) : ChatError

    companion object {
        fun from(raw: String): ChatError {
            val normalized = raw.lowercase()
            return when {
                "登录" in raw || "auth" in normalized || "unauthorized" in normalized ->
                    Auth(raw)
                // Codex only speaks Responses; chat-only gateways (e.g. dots) often 400 here.
                isResponsesProtocolMismatch(normalized) -> Model(raw)
                "模型" in raw || "provider" in normalized || "model" in normalized ->
                    Model(raw)
                "连接" in raw || "connect" in normalized || "timeout" in normalized ->
                    Network(raw)
                else -> Unknown(raw)
            }
        }

        /** True when the failure looks like Responses vs chat/completions mismatch. */
        fun isResponsesProtocolMismatch(normalized: String): Boolean {
            if ("chat/completions" in normalized && "responses" in normalized) return true
            if ("wire_api" in normalized && "chat" in normalized) return true
            if ("client_bad_request" in normalized) return true
            if ("invalid provider request" in normalized) return true
            if ("provider.client_bad_request" in normalized) return true
            // HTTP 400 on provider path without auth wording → treat as model/protocol.
            if ((" 400" in normalized || "status=400" in normalized || "http 400" in normalized ||
                    "400 bad request" in normalized) &&
                ("provider" in normalized || "responses" in normalized || "request" in normalized)
            ) {
                return true
            }
            return false
        }
    }
}

@Immutable
data class ChatUiState(
    val card: AgentCard? = null,
    val isConnecting: Boolean = true,
    val isConnected: Boolean = false,
    val isStreaming: Boolean = false,
    val isReconnecting: Boolean = false,
    val runtimeModel: String? = null,
    val runtimeProvider: String? = null,
    val composer: String = "",
    val attachments: List<ChatAttachment> = emptyList(),
    val isImportingAttachment: Boolean = false,
    val approval: ChatApproval? = null,
    /** L1 宿主工作区写操作审批（与 Codex sandbox 审批独立）。 */
    val hostWriteApproval: HostWriteApproval? = null,
    /** Pending `item/tool/requestUserInput` server request, if any. */
    val userInputRequest: ChatUserInputRequest? = null,
    /** Message typed while a turn was running and steering failed; sent on turn end. */
    val queued: QueuedChatMessage? = null,
    /** Formatted token usage of the last completed turn (technical detail mode only). */
    val lastTurnTokens: String? = null,
    /** Models offered by the bound provider for in-chat override (advanced mode). */
    val availableModels: List<CodexModelOption> = emptyList(),
    /** Per-chat model override; null uses the card-bound model. */
    val selectedModel: String? = null,
    /** Per-chat permission override; null inherits the effective default. */
    val selectedPermission: CodexPermissionLevel? = null,
    val error: ChatError? = null,
    /**
     * L1 真实目录状态条；null 表示未开启或不展示。
     * 说明：真实文件夹不会挂载进 Linux cwd。
     */
    val hostWorkspaceBanner: String? = null,
) {
    // Computed once at construction; copy() re-runs the constructor so this always
    // reflects the current field values. Sending while streaming steers the active
    // turn, so the composer only blocks on approval/user-input slots and disconnect.
    val canSend: Boolean =
        isConnected && !isConnecting &&
            (composer.isNotBlank() || attachments.isNotEmpty()) &&
            !isImportingAttachment &&
            approval == null &&
            hostWriteApproval == null &&
            userInputRequest == null &&
            queued == null
}

/** 宿主工作区写审批展示模型（ADR-0011）。 */
@Immutable
data class HostWriteApproval(
    val id: String,
    val summary: String,
)
